# MoveIt uses this configuration for controller management
trajectory_execution:
  allowed_execution_duration_scaling: 1.2
  allowed_goal_duration_margin: 0.5
  allowed_start_tolerance: 0.01

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager
moveit_simple_controller_manager:
  controller_names:
    - cobolege_controller

  cobolege_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - c2n6s000_joint_1
      - c2n6s000_joint_2
      - c2n6s000_joint_3
      - c2n6s000_joint_4
      - c2n6s000_joint_5
      - c2n6s000_joint_6
