# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    cobolege_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

cobolege_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - c2n6s000_joint_1
      - c2n6s000_joint_2
      - c2n6s000_joint_3
      - c2n6s000_joint_4
      - c2n6s000_joint_5
      - c2n6s000_joint_6
